# Generated by Django 5.1.2 on 2024-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.TextField(default='', null=True),
        ),
    ]
