# Generated by Django 5.1.2 on 2024-10-26 07:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_verified', models.BooleanField(default=False)),
                ('form_submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('hospital', models.CharField(max_length=255)),
                ('clinic', models.CharField(max_length=255, null=True)),
                ('license', models.CharField(max_length=255)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('medical_registration', models.CharField(max_length=255)),
                ('id_proof', models.FileField(upload_to='documents/')),
                ('medical_license', models.FileField(upload_to='documents/')),
                ('degree_certificate', models.FileField(upload_to='documents/')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
