# Generated by Django 5.1.2 on 2024-11-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_appointmentavailability_breaktime_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentavailability',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
