# Generated by Django 5.1.2 on 2024-11-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentavailability',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
