# Generated by Django 5.1.2 on 2024-11-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_appointmentavailability_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
