# Generated by Django 5.1.2 on 2024-12-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_delete_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='clinic',
        ),
        migrations.AddField(
            model_name='verification',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
